CREATE TABLE "quote_lines" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"quote_id" uuid NOT NULL,
	"position" integer NOT NULL,
	"source_kind" text,
	"source_id" uuid,
	"description" text NOT NULL,
	"unit_label" text NOT NULL,
	"quantity" numeric(14, 4) NOT NULL,
	"unit_price_minor" bigint NOT NULL,
	"discount_kind" text,
	"discount_value" bigint,
	"tax_rate_id" uuid,
	"tax_rate_name" text,
	"tax_rate_bps" integer,
	"gross_minor" bigint NOT NULL,
	"discount_minor" bigint NOT NULL,
	"tax_minor" bigint NOT NULL,
	"total_minor" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "quote_lines_quote_position_unique" UNIQUE("quote_id","position"),
	CONSTRAINT "quote_lines_position_not_negative" CHECK ("quote_lines"."position" >= 0),
	CONSTRAINT "quote_lines_quantity_positive" CHECK ("quote_lines"."quantity" > 0),
	CONSTRAINT "quote_lines_unit_price_not_negative" CHECK ("quote_lines"."unit_price_minor" >= 0),
	CONSTRAINT "quote_lines_source_kind" CHECK ("quote_lines"."source_kind" is null or "quote_lines"."source_kind" in ('product', 'service')),
	CONSTRAINT "quote_lines_discount_pair" CHECK (("quote_lines"."discount_kind" is null and "quote_lines"."discount_value" is null) or ("quote_lines"."discount_kind" in ('percent', 'amount') and "quote_lines"."discount_value" >= 0)),
	CONSTRAINT "quote_lines_tax_pair" CHECK (("quote_lines"."tax_rate_name" is null and "quote_lines"."tax_rate_bps" is null) or ("quote_lines"."tax_rate_name" is not null and "quote_lines"."tax_rate_bps" between 0 and 10000)),
	CONSTRAINT "quote_lines_amounts_not_negative" CHECK ("quote_lines"."gross_minor" >= 0 and "quote_lines"."discount_minor" >= 0 and "quote_lines"."tax_minor" >= 0 and "quote_lines"."total_minor" >= 0)
);
--> statement-breakpoint
CREATE TABLE "quotes" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"customer_id" uuid,
	"number" text,
	"revision" integer DEFAULT 1 NOT NULL,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"currency" char(3) NOT NULL,
	"tax_mode" text NOT NULL,
	"issue_date" date NOT NULL,
	"valid_until" date NOT NULL,
	"customer_snapshot" jsonb,
	"notes" text,
	"terms" text,
	"subtotal_minor" bigint DEFAULT 0 NOT NULL,
	"discount_total_minor" bigint DEFAULT 0 NOT NULL,
	"tax_total_minor" bigint DEFAULT 0 NOT NULL,
	"total_minor" bigint DEFAULT 0 NOT NULL,
	"sent_at" timestamp with time zone,
	"viewed_at" timestamp with time zone,
	"decided_at" timestamp with time zone,
	"decision_name" text,
	"decision_note" text,
	"decision_content_hash" text,
	"decision_ip" text,
	"decision_user_agent" text,
	"cancelled_at" timestamp with time zone,
	"cancel_reason" text,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "quotes_organization_id_id_unique" UNIQUE("organization_id","id"),
	CONSTRAINT "quotes_organization_number_unique" UNIQUE("organization_id","number"),
	CONSTRAINT "quotes_status" CHECK ("quotes"."status" in ('DRAFT', 'SENT', 'VIEWED', 'APPROVED', 'REJECTED', 'EXPIRED', 'CANCELLED')),
	CONSTRAINT "quotes_tax_mode" CHECK ("quotes"."tax_mode" in ('inclusive', 'exclusive')),
	CONSTRAINT "quotes_currency_iso" CHECK ("quotes"."currency" ~ '^[A-Z]{3}$'),
	CONSTRAINT "quotes_revision_positive" CHECK ("quotes"."revision" >= 1),
	CONSTRAINT "quotes_valid_until_after_issue" CHECK ("quotes"."valid_until" >= "quotes"."issue_date"),
	CONSTRAINT "quotes_sent_complete" CHECK ("quotes"."status" in ('DRAFT', 'CANCELLED') or ("quotes"."customer_id" is not null and "quotes"."number" is not null)),
	CONSTRAINT "quotes_totals_not_negative" CHECK ("quotes"."subtotal_minor" >= 0 and "quotes"."discount_total_minor" >= 0 and "quotes"."tax_total_minor" >= 0 and "quotes"."total_minor" >= 0)
);
--> statement-breakpoint
ALTER TABLE "quote_lines" ADD CONSTRAINT "quote_lines_quote_fk" FOREIGN KEY ("organization_id","quote_id") REFERENCES "public"."quotes"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_customer_fk" FOREIGN KEY ("organization_id","customer_id") REFERENCES "public"."customers"("organization_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "quotes_organization_status_valid_until_idx" ON "quotes" USING btree ("organization_id","status","valid_until");--> statement-breakpoint
CREATE INDEX "quotes_organization_updated_idx" ON "quotes" USING btree ("organization_id","updated_at" DESC NULLS LAST);