import { sql } from "drizzle-orm";
import { timestamp, uuid } from "drizzle-orm/pg-core";

// Shared column conventions (docs/foundation-proposal.md §C).

/** UUIDv7 primary key, generated by Postgres 18's native `uuidv7()`. */
export const id = () => uuid("id").primaryKey().default(sql`uuidv7()`);

/** `created_at` / `updated_at` as timestamptz; `updated_at` refreshes on update. */
export const timestamps = () => ({
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});
