import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";
import { haveIBeenPwned } from "better-auth/plugins";
import type { Database } from "@/db";
import { brand } from "@/config/brand";
import { passwordResetEmail, sendEmail, verifyEmailEmail } from "@/modules/notifications";
import { SESSION_POLICY } from "../domain/session-policy";
import { accounts, rateLimits, sessions, users, verifications } from "../schema";

export type AuthConfig = {
  /** Public base URL, e.g. https://app.tavi.ph. Also the only trusted origin. */
  baseURL: string;
  secret: string | undefined;
  /** Rate limiting is on in production (per Better Auth's own default). */
  rateLimit: boolean;
  /** Check new passwords against Have I Been Pwned (k-anonymity range API). */
  checkBreachedPasswords: boolean;
};

// Email delivery must never block or reveal anything to the caller: send in
// the background and log failures (timing-safe for password resets).
function deliver(send: Promise<void>) {
  send.catch((error: unknown) => {
    console.error("[auth] email delivery failed", error instanceof Error ? error.message : error);
  });
}

/**
 * Better Auth for identity and sessions only (docs/foundation-proposal.md §D).
 * Organizations, memberships and permissions stay in our own modules.
 * Kept free of `server-only` so integration tests can build an instance over
 * the test database; the app uses `getAuth()`.
 */
export function createAuth(db: Database, config: AuthConfig) {
  return betterAuth({
    appName: brand.name,
    baseURL: config.baseURL,
    secret: config.secret,
    trustedOrigins: [config.baseURL],
    telemetry: { enabled: false },
    database: drizzleAdapter(db, {
      provider: "pg",
      schema: {
        user: users,
        session: sessions,
        account: accounts,
        verification: verifications,
        rateLimit: rateLimits,
      },
    }),
    advanced: {
      // IDs are UUIDv7 generated by Postgres, like every other table.
      database: { generateId: false },
      cookiePrefix: "tavi",
    },
    emailAndPassword: {
      enabled: true,
      minPasswordLength: 12,
      maxPasswordLength: 128,
      autoSignIn: true,
      // Progressive verification: explore first, verify before sending (§D).
      requireEmailVerification: false,
      resetPasswordTokenExpiresIn: 30 * 60,
      revokeSessionsOnPasswordReset: true,
      sendResetPassword: async ({ user, url }) => {
        deliver(sendEmail(passwordResetEmail({ to: user.email, name: user.name, url })));
      },
    },
    emailVerification: {
      sendOnSignUp: true,
      autoSignInAfterVerification: true,
      expiresIn: 24 * 60 * 60,
      sendVerificationEmail: async ({ user, url }) => {
        deliver(sendEmail(verifyEmailEmail({ to: user.email, name: user.name, url })));
      },
    },
    session: {
      expiresIn: SESSION_POLICY.idleTimeoutSeconds,
      updateAge: SESSION_POLICY.renewAfterSeconds,
      freshAge: SESSION_POLICY.freshAuthSeconds,
      // Off: one indexed lookup per request buys instant revocation (§D).
      cookieCache: { enabled: false },
      additionalFields: {
        activeOrganizationId: { type: "string", required: false, input: false },
      },
    },
    rateLimit: {
      enabled: config.rateLimit,
      storage: "database",
      modelName: "rateLimit",
      window: 60,
      max: 100,
      customRules: {
        "/sign-in/email": { window: 60, max: 10 },
        "/sign-up/email": { window: 60, max: 10 },
        "/request-password-reset": { window: 15 * 60, max: 5 },
        "/send-verification-email": { window: 15 * 60, max: 5 },
      },
    },
    plugins: [
      haveIBeenPwned({
        enabled: config.checkBreachedPasswords,
        customPasswordCompromisedMessage:
          "This password has appeared in a data breach. Choose a different one.",
      }),
      // Must stay last: lets server actions set auth cookies.
      nextCookies(),
    ],
  });
}

export type Auth = ReturnType<typeof createAuth>;
