import { betterAuth } from "better-auth";
import { APIError } from "better-auth/api";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";
import { haveIBeenPwned } from "better-auth/plugins";
import type { Database } from "@/db";
import { brand } from "@/config/brand";
import { recordAuditEvent } from "@/modules/audit";
import { passwordResetEmail, sendEmail, verifyEmailEmail } from "@/modules/notifications";
import { LINK_LIFETIMES, PASSWORD_POLICY, passwordResetLifetime } from "../domain/auth-policy";
import { logger } from "@/shared/logger";
import { SESSION_POLICY } from "../domain/session-policy";
import { acceptedTermsVersion, TERMS_NOT_ACCEPTED, TERMS_REQUIRED_MESSAGE } from "../domain/terms";
import { accounts, rateLimits, sessions, users, verifications } from "../schema";

export type AuthConfig = {
  /** Public base URL, e.g. https://app.tavi.ph. Also the only trusted origin. */
  baseURL: string;
  secret: string | undefined;
  /** Rate limiting is on in production (per Better Auth's own default). */
  rateLimit: boolean;
  /** Check new passwords against Have I Been Pwned (k-anonymity range API). */
  checkBreachedPasswords: boolean;
};

// Email delivery must never block or reveal anything to the caller: send in
// the background and log failures (timing-safe for password resets).
function deliver(send: Promise<void>) {
  send.catch((error: unknown) => {
    logger.error("auth email delivery failed", { error });
  });
}

/**
 * Better Auth for identity and sessions only (docs/foundation-proposal.md §D).
 * Organizations, memberships and permissions stay in our own modules.
 * Kept free of `server-only` so integration tests can build an instance over
 * the test database; the app uses `getAuth()`.
 */
export function createAuth(db: Database, config: AuthConfig) {
  return betterAuth({
    appName: brand.name,
    baseURL: config.baseURL,
    secret: config.secret,
    trustedOrigins: [config.baseURL],
    telemetry: { enabled: false },
    database: drizzleAdapter(db, {
      provider: "pg",
      schema: {
        user: users,
        session: sessions,
        account: accounts,
        verification: verifications,
        rateLimit: rateLimits,
      },
    }),
    advanced: {
      // IDs are UUIDv7 generated by Postgres, like every other table.
      database: { generateId: false },
      cookiePrefix: "tavi",
    },
    emailAndPassword: {
      enabled: true,
      minPasswordLength: PASSWORD_POLICY.minLength,
      maxPasswordLength: PASSWORD_POLICY.maxLength,
      autoSignIn: true,
      // Progressive verification: explore first, verify before sending (§D).
      requireEmailVerification: false,
      resetPasswordTokenExpiresIn: LINK_LIFETIMES.passwordResetSeconds,
      revokeSessionsOnPasswordReset: true,
      onPasswordReset: async ({ user }) => {
        await recordAuditEvent(db, {
          action: "auth.password_reset",
          actorType: "user",
          actorId: user.id,
          entityType: "user",
          entityId: user.id,
        });
      },
      sendResetPassword: async ({ user, url }) => {
        deliver(sendEmail(passwordResetEmail({ to: user.email, name: user.name, url, expiresIn: passwordResetLifetime() })));
      },
    },
    emailVerification: {
      sendOnSignUp: true,
      autoSignInAfterVerification: true,
      expiresIn: LINK_LIFETIMES.emailVerificationSeconds,
      sendVerificationEmail: async ({ user, url }) => {
        deliver(sendEmail(verifyEmailEmail({ to: user.email, name: user.name, url })));
      },
    },
    user: {
      additionalFields: {
        // Sent by the sign-up form; checked and stamped in the create hook below.
        termsVersion: { type: "string", required: false, input: true },
        termsAcceptedAt: { type: "date", required: false, input: false },
      },
    },
    session: {
      expiresIn: SESSION_POLICY.idleTimeoutSeconds,
      updateAge: SESSION_POLICY.renewAfterSeconds,
      freshAge: SESSION_POLICY.freshAuthSeconds,
      // Off: one indexed lookup per request buys instant revocation (§D).
      cookieCache: { enabled: false },
      additionalFields: {
        activeOrganizationId: { type: "string", required: false, input: false },
      },
    },
    databaseHooks: {
      user: {
        create: {
          // No account without the current Terms of Service and Privacy
          // Notice (1.13b). The browser's checkbox is a convenience; this is
          // the rule. The time is the server's, never the client's.
          before: async (user) => {
            const termsVersion = acceptedTermsVersion(user.termsVersion);
            if (!termsVersion) {
              throw new APIError("BAD_REQUEST", { code: TERMS_NOT_ACCEPTED, message: TERMS_REQUIRED_MESSAGE });
            }
            return { data: { ...user, termsVersion, termsAcceptedAt: new Date() } };
          },
          after: async (user) => {
            await recordAuditEvent(db, {
              action: "auth.signed_up",
              actorType: "user",
              actorId: user.id,
              entityType: "user",
              entityId: user.id,
              metadata: { termsVersion: user.termsVersion },
            });
          },
        },
      },
      session: {
        create: {
          after: async (session) => {
            await recordAuditEvent(db, {
              action: "auth.signed_in",
              actorType: "user",
              actorId: session.userId,
              entityType: "session",
              entityId: session.id,
              ipAddress: session.ipAddress ?? null,
              userAgent: session.userAgent ?? null,
            });
          },
        },
      },
    },
    rateLimit: {
      enabled: config.rateLimit,
      storage: "database",
      modelName: "rateLimit",
      window: 60,
      max: 100,
      customRules: {
        "/sign-in/email": { window: 60, max: 10 },
        "/sign-up/email": { window: 60, max: 10 },
        "/request-password-reset": { window: 15 * 60, max: 5 },
        "/send-verification-email": { window: 15 * 60, max: 5 },
      },
    },
    plugins: [
      haveIBeenPwned({
        enabled: config.checkBreachedPasswords,
        customPasswordCompromisedMessage:
          "This password has appeared in a data breach. Choose a different one.",
      }),
      // Must stay last: lets server actions set auth cookies.
      nextCookies(),
    ],
  });
}

export type Auth = ReturnType<typeof createAuth>;
